#!/usr/bin/env bash

# Run tests and linting checks before commit

# Stash unstaged changes
git stash -q --keep-index

# Run tests
python3 manage.py test
TEST_EXIT_CODE=$?

# Run linting
pycodestyle .
LINT_EXIT_CODE=$?

# Unstash changes
git stash pop -q

# Check exit codes
if [ $TEST_EXIT_CODE -ne 0 ] || [ $LINT_EXIT_CODE -ne 0 ]; then
    echo "Tests or linting failed, commit aborted"
    exit 1
else
    exit 0
fi
