# this workflow builds a docker image and pushes it to dockerhub

name: TechHub Deployment
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run:  |
          cd src
          export KEY=${{ secrets.SECRET_KEY }}
          python manage.py test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout for building
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/techhub:latest
